version: "3"


services:
  pg:
    image: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    ports:
      - 5432:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  app:
    depends_on:
      - pg
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    restart: always
    build:
      context: .
    ports:
      - 3000:5000
    volumes:
      - ./db:/app/db
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
